version: '2'
name: nginx
services:
  nginx:
    image: nginx:1.23.1-alpine
    container_name: tomato-nginx
    networks:
      - tomato-network
    volumes:
      - ./packages/nginx/nginx-config:/etc/nginx
      - ./packages/nginx/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  nginx-config:
  letsencrypt:

networks:
  tomato-network:
    external: true