version: "3.9"
name: media-stack
services:
  deluge:
    profiles: ["to", "tomato-one"]
    image: linuxserver/deluge:latest
    container_name: potato-deluge
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./packages/deluge/config:/config
      - /storage/incomplete:/downloads
#      - /storage:/storage #use only if you mounted the hdd as /storage
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946
    networks:
      - tomato-network

  radarr:
    profiles: ["base", "radarr", "tomato-one", "tomato-two"]
    container_name: radarr
    image: linuxserver/radarr:latest
    networks:
      - tomato-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - ./packages/radarr/config:/config
      - ./packages/radarr/downloads:/downloads
#      - /storage:/storage #use only if you mounted the hdd as /storage
    restart: "unless-stopped"

  sonarr:
    profiles: ["base", "sonarr", "tomato-one", "tomato-two"]
    image: linuxserver/sonarr:latest
    container_name: tomato-sonarr
    networks:
      - tomato-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./packages/sonarr/config:/config
      - ./packages/sonarr/downloads:/downloads
#      - /storage:/storage #use only if you mounted the hdd as /storage
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    profiles: ["jackett", "tomato-one"]
    container_name: tomato-jackett
    image: linuxserver/jackett:latest
    networks:
      - tomato-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./packages/jackett/config:/config
      - ./packages/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    profiles: ["base", "jelly", "tomato-one", "tomato-two"]
    image: linuxserver/jellyfin:latest
    container_name: tomato-jellyfin
    networks:
      - tomato-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./packages/jellyfin/jellyfin-config:/config
      - ./packages/jellyfin/torrent-downloads:/storage
#      - /storage:/storage #use only if you mounted the hdd as /storage
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

  searcharr:
    container_name: potato-searcharr
    image: toddrob/searcharr:latest
    env_file: .env
    volumes:
      - ./packages/searcharr/data:/app/data
      - ./packages/searcharr/logs:/app/logs
      - ./packages/searcharr/settings.py:/app/settings.py
    environment:
      - TZ=Europe/Bucharest
    restart: unless-stopped
    network_mode: host

volumes:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  jellyfin-config:
  to-config:
  to-watch:

networks:
  tomato-network:
    external: true
